name: build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 3
    - uses: actions/setup-go@v4
      with:
        go-version: "^1.20"
    - name: go get
      run: go get -v -t
    - name: Test
      run: make test
    - name: Build
      if: startsWith(github.ref, 'refs/tags')
      env:
        CGO_ENABLED: 0
      run: make gzip
    - name: Release
      if: startsWith(github.ref, 'refs/tags')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: docker-ibug.gz
        draft: false
        prerelease: false
